### ISSUE TITLE
Errors when using module

### ISSUE THREAD

**Issue by dezinezync** [pusher-community/titanium_pusher_ios#3]
When I add the module to my tiapp.xml, and perform a clean build, I get the following errors: 

```
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] 
[ERROR] Error: Traceback (most recent call last):
  File "/Users/dezinezync/Library/Application Support/Titanium/mobilesdk/osx/2.1.1.GA/iphone/builder.py", line 1333, in main
    execute_xcode("iphonesimulator%s" % link_version,["GCC_PREPROCESSOR_DEFINITIONS=__LOG__ID__=%s DEPLOYTYPE=development TI_DEVELOPMENT=1 DEBUG=1 TI_VERSION=%s %s %s" % (log_id,sdk_version,debugstr,kroll_coverage)],False)
  File "/Users/dezinezync/Library/Application Support/Titanium/mobilesdk/osx/2.1.1.GA/iphone/builder.py", line 1239, in execute_xcode
    output = run.run(args,False,False,o)
  File "/Users/dezinezync/Library/Application Support/Titanium/mobilesdk/osx/2.1.1.GA/iphone/run.py", line 41, in run
    sys.exit(rc)
SystemExit: 65
```

When I remove the module, and perform a clean build again, it works. So I'm guessing the above is related to this module. Would really appreciate some help on this.

**Comment by rubenfonseca** [comment]
Hi! Can you please upload somewhere the build/iphone/build.log file please? I need that to see why it is failing. 

Also, which version of the module are you using?

**Comment by dezinezync** [comment]
You can find the build.log here: http://cl.ly/25362b0V1834

I downloaded the files from this repo again today morning. (8 hours ago)

**Comment by rubenfonseca** [comment]
Hi again :) Just uploaded a new 0.2 version to my branch that should fix this problem. Can you please replace your 0.2 version with that? Cheers!

**Comment by dezinezync** [comment]
Hello Ruben,

I downloaded 0.2. Got it to compile instantly, however, build.py only created a manifest file. There .a file was not created. 
Also, I got this error when building:

```

** BUILD SUCCEEDED **

lipo: no input files specified
lipo: Usage: lipo [input_file] ... [-arch <arch_type> input_file] ... [-info] [-detailed_info] [-output output_file] [-create] [-arch_blank <arch_type>] [-thin <arch_type>] [-remove <arch_type>] ... [-extract <arch_type>] ... [-extract_family <arch_type>] ... [-verify_arch <arch_type> ...] [-replace <arch_type> <file_name>] ...
Traceback (most recent call last):
  File "./build.py", line 201, in <module>
    package_module(manifest,mf,config)
  File "./build.py", line 180, in package_module
    zf.write('build/%s' % libname, '%s/%s' % (modulepath,libname))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 1031, in write
    st = os.stat(filename)
OSError: [Errno 2] No such file or directory: 'build/libcom.pusher.a'
```

Any idea, on what's happening here?

**Comment by rubenfonseca** [comment]
Not really. Did you download the source code from my branch? I was talking about downloading the binary on the "Downloads" section

**Comment by dezinezync** [comment]
Hello Ruben,

I downloaded the v0.2 file from the downloads section. The project built fine this time. Thank you for helping me out.  

Cheers.

Regards,
Nikhil.

## 

Nikh
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
