### ISSUE TITLE
Error Building Module on OS X 10.8 with TiMobile SDK 2.1.2.GA

### ISSUE THREAD

**Issue by cshirley** [pusher-community/titanium_pusher_ios#5]
Hello

I get the following error when I attempt to build the plugin

[WARN] please update the manifest key: 'license' to a non-default value
[WARN] please update the LICENSE file with your license text before distributing
Build settings from command line:
    SDKROOT = iphoneos5.1

=== BUILD NATIVE TARGET pusher OF PROJECT pusher WITH CONFIGURATION Release ===
Check dependencies

CompileC build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv7/CDataScanner.o libPusher/Vendor/TouchJSON/Source/CDataScanner.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios
    setenv LANG en_US.US-ASCII
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -std=c99 -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wreturn-type -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wformat -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-sign-compare -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.1.sdk -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion "-DIBOutlet=**attribute**((iboutlet))" "-DIBOutletCollection(ClassName)=**attribute**((iboutletcollection(ClassName)))" "-DIBAction=void)**attribute**((ibaction)" -miphoneos-version-min=5.1 -iquote /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-generated-files.hmap -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-own-target-headers.hmap -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-all-target-headers.hmap -iquote /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-project-headers.hmap -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/Release-iphoneos/include "-I/Library/Application Support/Titanium/mobilesdk/osx/2.1.2.GA/iphone/include" "-I/Library/Application Support/Titanium/mobilesdk/osx/2.1.2.GA/iphone/include/TiCore" -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/DerivedSources/armv7 -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/DerivedSources -F/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/Release-iphoneos -include /var/folders/yl/kb59ndwn1cv4v9tg60l_wrh80000gn/C/com.apple.Xcode.501/SharedPrecompiledHeaders/ComPusher_Prefix-ajsizqgykwiqfwcsxlusigiqybzz/ComPusher_Prefix.pch -MMD -MT dependencies -MF /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv7/CDataScanner.d --serialize-diagnostics /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv7/CDataScanner.dia -c /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/libPusher/Vendor/TouchJSON/Source/CDataScanner.m -o /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv7/CDataScanner.o

CompileC build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv7/PTPusherEventDispatcher.o libPusher/Library/PTPusherEventDispatcher.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios
    setenv LANG en_US.US-ASCII
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -std=c99 -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wreturn-type -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wformat -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-sign-compare -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.1.sdk -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion "-DIBOutlet=**attribute**((iboutlet))" "-DIBOutletCollection(ClassName)=**attribute**((iboutletcollection(ClassName)))" "-DIBAction=void)**attribute**((ibaction)" -miphoneos-version-min=5.1 -iquote /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-generated-files.hmap -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-own-target-headers.hmap -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-all-target-headers.hmap -iquote /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-project-headers.hmap -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/Release-iphoneos/include "-I/Library/Application Support/Titanium/mobilesdk/osx/2.1.2.GA/iphone/include" "-I/Library/Application Support/Titanium/mobilesdk/osx/2.1.2.GA/iphone/include/TiCore" -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/DerivedSources/armv7 -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/DerivedSources -F/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/Release-iphoneos -include /var/folders/yl/kb59ndwn1cv4v9tg60l_wrh80000gn/C/com.apple.Xcode.501/SharedPrecompiledHeaders/ComPusher_Prefix-ajsizqgykwiqfwcsxlusigiqybzz/ComPusher_Prefix.pch -MMD -MT dependencies -MF /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv7/PTPusherEventDispatcher.d --serialize-diagnostics /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv7/PTPusherEventDispatcher.dia -c /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/libPusher/Library/PTPusherEventDispatcher.m -o /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv7/PTPusherEventDispatcher.o

CompileC build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv6/ComPusherModule.o Classes/ComPusherModule.m normal armv6 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios
    setenv LANG en_US.US-ASCII
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv6 -fmessage-length=0 -std=c99 -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wreturn-type -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wformat -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-sign-compare -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.1.sdk -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion "-DIBOutlet=**attribute**((iboutlet))" "-DIBOutletCollection(ClassName)=**attribute**((iboutletcollection(ClassName)))" "-DIBAction=void)**attribute**((ibaction)" -miphoneos-version-min=5.1 -iquote /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-generated-files.hmap -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-own-target-headers.hmap -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-all-target-headers.hmap -iquote /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-project-headers.hmap -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/Release-iphoneos/include "-I/Library/Application Support/Titanium/mobilesdk/osx/2.1.2.GA/iphone/include" "-I/Library/Application Support/Titanium/mobilesdk/osx/2.1.2.GA/iphone/include/TiCore" -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/DerivedSources/armv6 -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/DerivedSources -F/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/Release-iphoneos -include /var/folders/yl/kb59ndwn1cv4v9tg60l_wrh80000gn/C/com.apple.Xcode.501/SharedPrecompiledHeaders/ComPusher_Prefix-gnjwynlgejngcvbpmyrbzgejyswb/ComPusher_Prefix.pch -MMD -MT dependencies -MF /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv6/ComPusherModule.d --serialize-diagnostics /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv6/ComPusherModule.dia -c /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/Classes/ComPusherModule.m -o /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv6/ComPusherModule.o
In file included from /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/Classes/ComPusherModule.m:7:
/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/Classes/ComPusherModule.h:7:9: fatal error: 'TiModule.h' file not found
# import "TiModule.h"

```
    ^
```

1 error generated.

CompileC build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv7/PTTargetActionEventListener.o libPusher/Library/PTTargetActionEventListener.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios
    setenv LANG en_US.US-ASCII
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -std=c99 -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wreturn-type -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wformat -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-sign-compare -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.1.sdk -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion "-DIBOutlet=**attribute**((iboutlet))" "-DIBOutletCollection(ClassName)=**attribute**((iboutletcollection(ClassName)))" "-DIBAction=void)**attribute**((ibaction)" -miphoneos-version-min=5.1 -iquote /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-generated-files.hmap -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-own-target-headers.hmap -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-all-target-headers.hmap -iquote /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/ComPusher-project-headers.hmap -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/Release-iphoneos/include "-I/Library/Application Support/Titanium/mobilesdk/osx/2.1.2.GA/iphone/include" "-I/Library/Application Support/Titanium/mobilesdk/osx/2.1.2.GA/iphone/include/TiCore" -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/DerivedSources/armv7 -I/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/DerivedSources -F/Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/Release-iphoneos -include /var/folders/yl/kb59ndwn1cv4v9tg60l_wrh80000gn/C/com.apple.Xcode.501/SharedPrecompiledHeaders/ComPusher_Prefix-ajsizqgykwiqfwcsxlusigiqybzz/ComPusher_Prefix.pch -MMD -MT dependencies -MF /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv7/PTTargetActionEventListener.d --serialize-diagnostics /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv7/PTTargetActionEventListener.dia -c /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/libPusher/Library/PTTargetActionEventListener.m -o /Users/cshirley/Documents/Titanium_Studio_Workspace/tradestream/titanium_pusher_ios/build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv7/PTTargetActionEventListener.o

*\* BUILD FAILED **

The following build commands failed:
    CompileC build/pusher.build/Release-iphoneos/pusher.build/Objects-normal/armv6/ComPusherModule.o Classes/ComPusherModule.m normal armv6 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild failed

**Comment by rubenfonseca** [comment]
check your `titanium.xcconfig` file and adjust your Titanium SDK version and path

**Comment by danielmcgrath** [comment]
I'm stuck on this issue as well. My `titanium.xconfig` is pointing at the proper SDK version (`3.1.1.GA`) and path, but I can't get this module to compile at all. Do you have any ideas?

**Comment by rubenfonseca** [comment]
@Hovertruck what exact error are you getting? Can you please GIST it?

**Comment by danielmcgrath** [comment]
Hey Ruben, thanks for responding!

This is what I encounter when I attempt to compile: https://gist.github.com/Hovertruck/5966705

I also attempted downloading the latest binary from your fork of the repo, but when I tried to include it in my project I got this error: https://gist.github.com/Hovertruck/5966785

Any idea what I'm missing here? :\

**Comment by rubenfonseca** [comment]
Hey Hovertruck, for the first problem, you need to checkout the submodules from the repository:

```
$ git submodule init
$ git submodule update
```

As for the second problem, I will look into it. I know what the problem is but I've just started some vacations and I'll be back by the middle of next week.

**Comment by danielmcgrath** [comment]
I did init the submodule, unfortunately, and still encountered the issue.

Please enjoy your vacation! :)

**Comment by rubenfonseca** [comment]
ok then try this 

```
$ git submodule update --init --recursive
```

because I think you're missing a dependency of a dependency :S

**Comment by danielmcgrath** [comment]
Hi there! Hope your vacation(s) were enjoyable.

When trying to perform `git submodule update --init --recursive`, I get the following error message:

```
Cloning into Vendor/Mocky...
remote: Counting objects: 2191, done.
remote: Compressing objects: 100% (1149/1149), done.
remote: Total 2191 (delta 1016), reused 2120 (delta 962)
Receiving objects: 100% (2191/2191), 833.03 KiB | 1.37 MiB/s, done.
Resolving deltas: 100% (1016/1016), done.
fatal: reference is not a tree: 0401394772647745131634e3eab8f7bb3340ee43
Unable to checkout '0401394772647745131634e3eab8f7bb3340ee43' in submodule path 'Vendor/Mocky'
Failed to recurse into submodule path 'libPusher'
```
